# Generated by Django 4.2.4 on 2023-08-04 08:44

import os
import sys

from django.db import connection, migrations, models, transaction


class Migration(migrations.Migration):
    initial = True

    @transaction.atomic
    def import_data(apps, schema_editor):
        with open(os.path.join(sys.path[0], "web/migrations/data.sql"), "r") as f:
            data = f.read()
            with connection.cursor() as cursor:
                for sql in filter(
                    lambda text: len(text) > 0,
                    map(lambda text: text.strip(), data.split(";")),
                ):
                    cursor.execute(sql)

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "username",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=80)),
                ("surname", models.CharField(max_length=80)),
                ("password", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="CashAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=80)),
                ("username", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=80)),
                ("availableBalance", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CreditAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cashAccountId", models.IntegerField()),
                ("number", models.CharField(max_length=80)),
                ("username", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=80)),
                ("availableBalance", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=80)),
                ("amount", models.FloatField()),
                ("availableBalance", models.FloatField()),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fromAccount", models.IntegerField()),
                ("toAccount", models.IntegerField()),
                ("description", models.CharField(max_length=80)),
                ("amount", models.FloatField()),
                ("fee", models.FloatField()),
                ("username", models.CharField(max_length=80)),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.RunPython(import_data),
    ]
